import { useRef, useState, type FormEvent } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { submitDiagnostico, type DiagnosticLead } from '../services/leads'
import { useUtm } from '../hooks/useUtm'
import { SEO } from '../components/SEO'

const fields = [['name', 'Nome *'], ['email', 'E-mail corporativo *'], ['company', 'Empresa *'], ['role', 'Cargo'], ['phone', 'Telefone/WhatsApp'], ['segment', 'Segmento'], ['size', 'Porte'], ['moment', 'Momento'], ['deadline', 'Prazo desejado'], ['source', 'Como conheceu o CITi']] as const

export function Diagnostico() {
  const [params] = useSearchParams(); const utm = useUtm(); const [form, setForm] = useState<Record<string, string>>({}); const [error, setError] = useState(''); const [status, setStatus] = useState<'idle' | 'loading' | 'success'>('idle'); const firstError = useRef<HTMLInputElement>(null)
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.name || !form.email || !form.company || (form.problem ?? '').length < 30 || !form.contactConsent) { setError('Preencha os campos obrigatórios. O problema deve ter pelo menos 30 caracteres.'); firstError.current?.focus(); return } setError(''); setStatus('loading'); const payload: DiagnosticLead = { ...form, name: form.name, email: form.email, company: form.company, problem: form.problem, origem: params.get('origem') ?? '', referencia: document.referrer, ...utm }; await submitDiagnostico(payload); setStatus('success') }
  return <><SEO title="Solicitar diagnóstico" description="Conte o problema. A gente ajuda a entender." /><section className="diagnostic-page container"><div className="diagnostic-intro"><span className="eyebrow">Solicitar diagnóstico</span><h1>Conte o <strong>problema.</strong><br />A gente ajuda a <strong>entender.</strong></h1><p>Uma conversa inicial para organizar o desafio e descobrir caminhos possíveis, sem compromisso.</p><h2>Como funciona</h2><ol><li>Você conta o desafio.</li><li>Nosso time analisa e entra em contato.</li><li>Conversa de Discovery sem compromisso.</li></ol><small>TODO: confirmar prazo de retorno com o Comercial.</small></div><div className="diagnostic-card">{status === 'success' ? <div className="success-state"><span className="eyebrow">Recebemos sua mensagem</span><h2>Obrigado por <strong>compartilhar.</strong></h2><p>Nosso time vai analisar o contexto e entrar em contato.</p><Link className="button-primary" to="/blog/artigos">Enquanto isso, leia nossos artigos</Link></div> : <form onSubmit={submit} noValidate><h2>Sobre o seu desafio</h2>{fields.map(([key, label], index) => <label key={key}>{label}<input ref={index === 0 ? firstError : undefined} type={key === 'email' ? 'email' : 'text'} value={form[key] ?? ''} onChange={(event) => update(key, event.target.value)} /></label>)}<label>Qual problema de negócio você quer resolver? *<textarea minLength={30} value={form.problem ?? ''} onChange={(event) => update('problem', event.target.value)} /><small>{(form.problem ?? '').length} caracteres</small></label><label className="check-label"><input type="checkbox" checked={Boolean(form.contactConsent)} onChange={(event) => update('contactConsent', String(event.target.checked))} /> Autorizo o CITi a entrar em contato sobre esta solicitação.</label><label className="check-label"><input type="checkbox" checked={Boolean(form.newsletter_optin)} onChange={(event) => update('newsletter_optin', String(event.target.checked))} /> Quero receber a newsletter do CITi.</label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button-primary" disabled={status === 'loading'}>{status === 'loading' ? 'Enviando...' : 'Enviar solicitação'}</button><small>Ao enviar, você concorda com nossa <a href="#">Política de privacidade</a>.</small></form>}</div></section></>
}
